# Generated by Django 4.2.3 on 2023-07-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_is_published_material_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='просмотры'),
        ),
    ]
